### ISSUE TITLE
Vue files

### ISSUE THREAD

**Issue by keyurshah** [pouyakary/comment#9]
Is there anyway to support .vue files?

Thanks for the wonderful project!

**Comment by pmkary** [comment]
Hi @keyurshah! Thanks for using Comment !

I'm not a Vue user so I have no idea how do you comment in Vue. I know that it's like HTML + JS and so there are two kinds of comments there. The problem is comment cannot recognize the JS in the Vue. So I can only configure it to write HTML like comments. 

You have any ideas?

**Comment by keyurshah** [comment]
Yeah it’s a little confusing. It can actually have multiple languages inside each type of file as well (pug, traditional html, markdown, etc..,)

If it’s possible to specify a default comment style, the i can just keep JavaScript as the default if it can’t recognize the file? 

Looks like it’s defaulting to think right now, and if it can be a user workspace option, then i can configure it per project. Thanks!

**Comment by pmkary** [comment]
that is a good idea. I'll try to add it in the next version.
